### ISSUE TITLE
Use default branch instead of master when no branch specified

### ISSUE THREAD

**Issue by vjda** [jenkins-x/updatebot#70]
Currently we have an `.updatebot.yml` as follows:

```yaml
  organisations:
  - name: myorg
    includes:
    - demo-*
    excludes:
    - *-WIP
```

We are using `develop` as default branch in every repository `demo-*`. When `updatebot` clones them, it uses `develop` as the default branch, but when it performs the command `push-regex -r [search_regex] -v replace_value files`, it always changes to `master` in every repository before replacing with the value.

It would be great to use the default branch when there is no a `github.organisations.repositories.branch: develop` in `.updatebot.yml`.
